### PR TITLE
Clean HTML & CSS

### PR DESCRIPTION
**Pull request by noplanman**
This PR is a rewrite of all HTML files and the corresponding CSS.
The file names have been renamed to be typo-free and match a general guideline.

I know it's a big PR, but most changes are structural, not functional.

### CODE REVIEW

**Comment by pparent76** [comment]
Hi,

The create account page seems broken.

Also on first page (and is some others), there are gaps, that seem strange.

See screenshots.

Pierre.

create-acounts
omb-screen

**Comment by noplanman** [comment]
I've fixed the broken pages. It was due to the % character that needs escaping in cgi scripts.

Regarding the spaces, that's because the boxes have a fixed size and the content is aligned to top and bottom. Titles are aligned to the top, content to the bottom. On the pages that have very little content, there is a space in the middle, I know.
Since we'll be switching to Bootstrap at some point, I didn't think it would make sense to go overly OCD and perfectionist on it.

Feel free to modify anything you like on it 👍
You can PR to my branch to make it easier to merge.

**Comment by pparent76** [comment]
Concerning the gap using  "min-height" CSS proprety for content should make it shouldn't it?

**Comment by noplanman** [comment]
@pparent76 You're absolutely right, I've committed a fix, setting the content height to at least 50%. Now, when there is only a bit of content, it's more in the middle.

Give it a try.

**Pull request merged**
